{% set name = "pandarallel" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandarallel-{{ version }}.tar.gz
  sha256: e36f16d7057a1728f9f3a6ef25ca50e01e382eb10d8be580a4881c210be6ce3a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill
    - python >=3.6
    - pandas

test:
  imports:
    - pandarallel
    - pandarallel.data_types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nalepae/pandarallel
  summary: An easy to use library to speed up computation (by parallelizing on multi CPUs) with pandas.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
